chown fakeroot:fakeroot create_dir
chown fakeroot:fakeroot fget
chown fakeroot:fakeroot fput
chown fakeroot:fakeroot ls
chown fakeroot:fakeroot do_exec
chown fakeroot:fakeroot getacl
chown fakeroot:fakeroot setacl
chown fakeroot:fakeroot fput_encrypt
chown fakeroot:fakeroot fget_decrypt
